export * from './card-type-a/card-type-a.component';
export * from './news/news.component';
export * from './card-type-b/card-type-b.component';
export * from './card-type-c/card-type-c.component';
export * from './comments/comments.component';
export * from './tags/tags.component';
export * from './empty-list/empty-list.component';
export * from './loading/loading.component';
export * from './component.module';